<?php

namespace Services;

use Tests\TestCase;
use App\Models\User;
use App\Models\Result;
use App\Models\Course;
use App\Services\UserService;
use Illuminate\Foundation\Testing\RefreshDatabase;

class UserServiceTest extends TestCase
{
    use RefreshDatabase;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->service = new UserService();
    }

    /** @test */
    public function canDelete()
    {
        $this->assertDatabaseCount(Result::class, 0);

        $user = User::factory()->create();
        Course::factory()->count(5)->create();
        Result::factory()->count(5)->create();

        $this->assertDatabaseCount(Result::class, 5);

        $userResultCount = Result::whereUserId($user->id)->count();

        $this->service->delete($user);

        $this->assertDatabaseCount(Result::class, 5 - $userResultCount);
    }
}
